### ISSUE TITLE
Doesn't import KML file if points don't have height

### ISSUE THREAD

**Issue by shlembo598** [sun-jiao/geoxml#2]
If the points don't have height like in this example:

`<kml xmlns="http://www.opengis.net/kml/2.2"><Placemark><name>01:05:3305001:1171</name><description>text</description><Style><LineStyle><color>FF143C6E</color><width>1</width></LineStyle><PolyStyle><fill>1</fill><color>9914F0FF</color></PolyStyle></Style><MultiGeometry><Polygon><outerBoundaryIs><LinearRing><coordinates>39.02912307321375,44.95823565821833 39.02908207410419,44.9571912212927 39.0298317721077,44.95718293203473 39.029814201060745,44.95656537894694 39.03139559528691,44.956548800248974 39.031829014445194,44.95793310503306 39.02912307321375,44.95823565821833</coordinates></LinearRing></outerBoundaryIs></Polygon></MultiGeometry></Placemark></kml>`

GeoXml.fromKmlString(data)  result is  GeoXml[1.1,,null,[],[Rte[01:05:3305001:1171,null,{},[]]],[],{}]

**Comment by sun-jiao** [comment]
![image](https://github.com/sun-jiao/geoxml/assets/14086980/8093cd01-2dd5-4ba1-98b2-47e096061f25)

Fixed and I'll update the package.

**Comment by sun-jiao** [comment]
The package has been updated to 2.5.2.
